In [2]:
!python --version

Python 3.10.12


In [ ]:
import numpy as np
import urllib
import tensorflow as tf

try:
  from tensorflow.lite.experimental.microfrontend.python.ops import audio_microfrontend_op as frontend_op  # pylint:disable=g-import-not-at-top
except ImportError:
  frontend_op = None

In [ ]:
import torchaudio
from torchaudio.utils import download_asset

import matplotlib.pyplot as plt

import IPython.display as ipd

In [ ]:
SAMPLE_WAV = download_asset("tutorial-assets/Lab41-SRI-VOiCES-src-sp0307-ch127535-sg0042.wav")

100%|██████████| 106k/106k [00:00<00:00, 2.08MB/s]


## Read Audio

In [ ]:
SAMPLE_WAV

'/root/.cache/torch/hub/torchaudio/tutorial-assets/Lab41-SRI-VOiCES-src-sp0307-ch127535-sg0042.wav'

In [ ]:
wav_loader = tf.io.read_file(SAMPLE_WAV)
wav_decoder, sr = tf.audio.decode_wav(wav_loader,
                                  desired_channels = 1)
wav = wav_decoder
wav

<tf.Tensor: shape=(54400, 1), dtype=float32, numpy=
array([[0.01831055],
       [0.01803589],
       [0.01797485],
       ...,
       [0.00183105],
       [0.00189209],
       [0.00320435]], dtype=float32)>

In [ ]:
micro_frontend = frontend_op.audio_microfrontend(tf.cast(tf.multiply(wav, 32768), tf.int16),
                                                 sample_rate = sr,
                                                 window_size = 30,
                                                 window_step = 10,
                                                 num_channels = 40,
                                                 out_type = tf.float32)
micro_frontend.shape

TensorShape([338, 40])

In [ ]:
micro_frontend.numpy()

array([[579., 507., 555., ..., 446., 451., 455.],
       [567., 507., 547., ..., 414., 435., 401.],
       [540., 471., 541., ..., 396., 437., 366.],
       ...,
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]], dtype=float32)

In [ ]:
micro_frontend

<tf.Tensor 'AudioMicrofrontend:0' shape=(19, 40) dtype=float32>