## Set up Tensorflow

In [1]:
import tensorflow as tf
print('Tensorflow version:', tf.__version__)

from tensorflow import keras

Tensorflow version: 2.15.0


## Load dataset

In [2]:
mnist = keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [14]:
x_train.shape

(60000, 28, 28)

## Build a machine learning model

In [3]:
model = keras.models.Sequential([
    keras.layers.Conv2D(32, 3, activation = 'relu', input_shape = (28, 28, 1)),
    keras.layers.Flatten(),
    keras.layers.Dense(128, activation = 'relu'),
    keras.layers.Dropout(0,1),
    keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.0385754 ,  0.04039606,  0.12343574,  0.04651459,  0.03998798,
        -0.05119783,  0.01850443, -0.06880306,  0.00494115,  0.11461953]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()


array([[0.10062224, 0.10080561, 0.10953385, 0.10142428, 0.10076448,
        0.09198266, 0.09862279, 0.09037746, 0.09729417, 0.10857242]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

In [7]:
model.compile(optimizer = 'adam',
              loss = loss_fn,
              metrics = ['accuracy'])

## Train and evaluate your model

In [8]:
model.fit(x_train, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 84s 45ms/step - loss: 0.1378 - accuracy: 0.9589
Epoch 2/5
1875/1875 [==============================] - 74s 39ms/step - loss: 0.0435 - accuracy: 0.9867
Epoch 3/5
1875/1875 [==============================] - 75s 40ms/step - loss: 0.0238 - accuracy: 0.9924
Epoch 4/5
1875/1875 [==============================] - 75s 40ms/step - loss: 0.0142 - accuracy: 0.9954
Epoch 5/5
1875/1875 [==============================] - 74s 40ms/step - loss: 0.0107 - accuracy: 0.9961


In [18]:
x_train = x_train[..., tf.newaxis].astype('float32')
x_test = x_test[..., tf.newaxis].astype('float32')

In [19]:
model = keras.models.Sequential([
    keras.layers.Conv2D(32, 3, activation = 'relu'),
    keras.layers.Flatten(),
    keras.layers.Dense(128, activation = 'relu'),
    keras.layers.Dropout(0,1),
    keras.layers.Dense(10)
])

In [20]:
model.build(input_shape = (None, 28, 28, 1))
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.04925716,  0.080033  ,  0.03929243,  0.00712162, -0.00574363,
         0.02005523,  0.1183989 ,  0.00142318, -0.09378353,  0.0615611 ]],
      dtype=float32)

In [21]:
model.compile(optimizer = 'adam',
              loss = loss_fn,
              metrics = ['accuracy'])

In [22]:
model.fit(x_train, y_train, epochs = 1)

1875/1875 [==============================] - 79s 42ms/step - loss: 0.1411 - accuracy: 0.9577


In [24]:
class MyModel(keras.Model):
  def __init__(self):
    super().__init__()
    self.conv1 = keras.layers.Conv2D(32, 3, activation='relu')
    self.flatten = keras.layers.Flatten()
    self.d1 = keras.layers.Dense(128, activation='relu')
    self.d2 = keras.layers.Dense(10)

  def call(self, x):
    x = self.conv1(x)
    x = self.flatten(x)
    x = self.d1(x)
    return self.d2(x)

# Create an instance of the model
model = MyModel()

In [25]:
model.build(input_shape = (None, 28, 28, 1))
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.01477384, -0.08500269,  0.02359105,  0.04992038, -0.01681152,
         0.0006392 ,  0.02808785,  0.01763603,  0.05337856,  0.06182326]],
      dtype=float32)

In [26]:
model.compile(optimizer = 'adam',
              loss = loss_fn,
              metrics = ['accuracy'])

In [27]:
model.fit(x_train, y_train, epochs = 1)

1875/1875 [==============================] - 76s 40ms/step - loss: 0.1340 - accuracy: 0.9600
